Lesson5
KabStas/CourseProject pull request #3
Opened 2020-11-08 11:11 UTC by KabStas

2020-11-09 16:50 UTC, chrnsv requested changes

2020-11-09 16:50 UTC, chrnsv commented on courseProject/Sources/courseProject/Arguments.swift
> +    case search (key: String?, language: String?)
Пробел перед скобкой лишний

2020-11-09 16:50 UTC, chrnsv commented on courseProject/Sources/courseProject/ArgumentsParser.swift
> +                print(Commands.helpMessage())
Давай подумаем как можно получать помощь в виде строки и печатать ее в том же месте, где печатаем все остальные результаты

2020-11-09 16:50 UTC, chrnsv commented on courseProject/Sources/courseProject/Delete.swift
> +        self.dict = GettingData()
Зависимости должны передаваться в класс, иначе получается что реализация класса `Delete` зависит от конкретных классов `GettingData` и `PuttingData`, а не от абстрактных протоколов

2020-11-09 16:50 UTC, chrnsv commented on courseProject/Sources/courseProject/Delete.swift
> +    func deletingValuesFromDictionary (language: String) -> [String: [String: String]] {
Давай повсеместно избавимся от этого пробела

2020-11-09 16:50 UTC, chrnsv commented on courseProject/Sources/courseProject/Delete.swift
> +                dictionary[key] = nil
немного странно, что все остальное делается через отдельные функции, а это прямо здесь, понятно, что одна строка, но все же

2020-11-09 16:50 UTC, chrnsv commented on courseProject/Sources/courseProject/Delete.swift
> +        var dictionary = dict.creatingDictionary()
словарь создается здесь и в функциях, получается несколько избыточно, учитывая, что это не самая дешевая операция по времени

2020-11-09 16:50 UTC, chrnsv commented on courseProject/Sources/courseProject/DeleteProtocol.swift
> +    func deletingValuesFromDictionary (language: String) -> [String: [String: String]]
А зачем эта и следующая функция в протоколе, если мы е нигде не используем отдельно? Лучше оставить ее только в реализации и сделать приватной

2020-11-09 16:50 UTC, chrnsv commented on courseProject/Sources/courseProject/GettingData.swift
> +        var dictionary: [String: [String: String]] = [:]
Вот тут инициализация

2020-11-09 16:50 UTC, chrnsv commented on courseProject/Sources/courseProject/GettingData.swift
> +            dictionary = [:]
И вот тут такая же инициализация. Зачем?)

2020-11-09 16:50 UTC, chrnsv commented on courseProject/Sources/courseProject/PuttingData.swift
> +        guard let path = Bundle.module.url(forResource: "dict", withExtension: "json") else {return}
Обычно, разносим на 3 строки, но тут кому как нравится, но пробелы до и после `return` точно стоит поставить

2020-11-09 16:50 UTC, chrnsv commented on courseProject/Sources/courseProject/Search.swift
> +
Лишний ввод

2020-11-09 16:50 UTC, chrnsv commented on courseProject/Sources/courseProject/Search.swift
> +        //let dictionary = dict.creatingDictionary()
Вот не используется же, а строку оставил и инициализацию оставил

2020-11-09 16:50 UTC, chrnsv commented on courseProject/Sources/courseProject/Search.swift
> +    func searching(key: String?, language: String?) {
Немного странная реализация получилась, по сути класс с названием `Search` ничего не ищет, он только определяет по аргументам как нужно искать, а класс, который должен отвечать за вывод как раз что-то ищет и только потом выводит. Получается, что у этого класса половина функции, а у того сразу две – поиск и вывод

2020-11-09 16:50 UTC, chrnsv commented on courseProject/Sources/courseProject/main.swift
> +        if let key: String = key, let language: String = language {
А зачем здесь проверять аргументы на `nil`, чтобы потом еще раз проверять эти же аргументы на `nil` внутри класса?)

2020-11-10 11:16 UTC, KabStas commented on courseProject/Sources/courseProject/Arguments.swift
> +    case search (key: String?, language: String?)
Для восприятия мне так удобнее, нет скученности... Исправил )

2020-11-10 12:48 UTC, KabStas commented on courseProject/Sources/courseProject/Delete.swift
> +    func deletingValuesFromDictionary (language: String) -> [String: [String: String]] {
Сделано

2020-11-10 13:07 UTC, KabStas commented on courseProject/Sources/courseProject/ArgumentsParser.swift
> +                print(Commands.helpMessage())
Исправил

2020-11-10 13:09 UTC, KabStas commented on courseProject/Sources/courseProject/Delete.swift
> +                dictionary[key] = nil
Исправил. Сделал отдельную функцию

2020-11-10 13:22 UTC, KabStas commented on courseProject/Sources/courseProject/Delete.swift
> +        var dictionary = dict.creatingDictionary()
Исправил. Словарь создается в одном месте и передается в функции

2020-11-10 13:24 UTC, KabStas commented on courseProject/Sources/courseProject/DeleteProtocol.swift
> +    func deletingValuesFromDictionary (language: String) -> [String: [String: String]]
Исправил

2020-11-10 13:27 UTC, KabStas commented on courseProject/Sources/courseProject/GettingData.swift
> +        var dictionary: [String: [String: String]] = [:]
Убрал инициализацию тут

2020-11-10 13:27 UTC, KabStas commented on courseProject/Sources/courseProject/GettingData.swift
> +            dictionary = [:]
Здесь оставил

2020-11-10 13:32 UTC, KabStas commented on courseProject/Sources/courseProject/PuttingData.swift
> +        guard let path = Bundle.module.url(forResource: "dict", withExtension: "json") else {return}
теперь 3 строки )

2020-11-10 13:32 UTC, KabStas commented on courseProject/Sources/courseProject/Search.swift
> +
убрал

2020-11-10 13:33 UTC, KabStas commented on courseProject/Sources/courseProject/Search.swift
> +        //let dictionary = dict.creatingDictionary()
убрал )

2020-11-10 14:25 UTC, KabStas commented on courseProject/Sources/courseProject/Search.swift
> +    func searching(key: String?, language: String?) {
Исправил. Search только ищет, Outputting только выводит

2020-11-10 14:43 UTC, KabStas commented on courseProject/Sources/courseProject/main.swift
> +        if let key: String = key, let language: String = language {
убрал здесь, оставил в классе

2020-11-11 17:06 UTC, chrnsv requested changes

2020-11-11 17:06 UTC, chrnsv commented on courseProject/Sources/courseProject/Delete.swift
> +        for (word, translations) in dictionary {
Получается что мы и ищем и выводим в одном месте, не очень хорошо (пусть и через отдельный класс, но решаем что и как выводить здесь)

2020-11-11 17:06 UTC, chrnsv commented on courseProject/Sources/courseProject/GetData.swift
> +
Почему-то всегда есть пропуск строки после объявления функции, но нет перед закрывающейся скобкой, можно и так оставить, просто логику не понял:)

2020-11-11 17:06 UTC, chrnsv commented on courseProject/Sources/courseProject/Output.swift
> +    func outputtingSearchResults(string: String, value: String, boolean: Bool) {
по названиям string и boolean не очень понятно что там за значения передаются

2020-11-11 17:06 UTC, chrnsv commented on courseProject/Sources/courseProject/Output.swift
> +        print(Commands.helpMessage())
Опять класс Output что-то знает про класс Commands

2020-11-11 17:06 UTC, chrnsv commented on courseProject/Sources/courseProject/PutDataProtocol.swift
> +    func writingToFile(dictionary: [String: [String: String]])
Опять что-то про файл

2020-11-11 17:06 UTC, chrnsv commented on courseProject/Sources/courseProject/Search.swift
> +                                output.outputtingSearchResults(string: value)
Ух какая елочка

2020-11-11 17:06 UTC, chrnsv commented on courseProject/Sources/courseProject/Search.swift
> +                                output.outputtingSearchResults(string: value)
А вот так не подойдет?
```swift
if let word = dictionary[key][language] {
    output.outputtingSearchResults(string: value)
}
else {
    output.outputtingSearchResults(string: "Not found")
}
```

2020-11-11 17:06 UTC, chrnsv commented on courseProject/Sources/courseProject/Search.swift
> +                                output.outputtingSearchResults(string: value)
Иначе получается, что положили данные в словарь, но не используем никаких его преимуществ

2020-11-12 11:38 UTC, KabStas commented on courseProject/Sources/courseProject/GetData.swift
> +
Исправил

2020-11-12 14:47 UTC, KabStas commented on courseProject/Sources/courseProject/Search.swift
> +                                output.outputtingSearchResults(string: value)
Подойдет ) Спасибо

2020-11-12 14:57 UTC, KabStas commented on courseProject/Sources/courseProject/Delete.swift
> +        for (word, translations) in dictionary {
Этот цикл я добавил, чтобы видеть изменения, которые произошли после удаления. Неудачное название для функции outputtingSearchResults поменял на outputtingResults.

2020-11-12 15:01 UTC, KabStas commented on courseProject/Sources/courseProject/Output.swift
> +    func outputtingSearchResults(string: String, value: String, boolean: Bool) {
Исправил на (key: value: alternativeOutput:)

2020-11-12 18:08 UTC, chrnsv requested changes

2020-11-12 18:08 UTC, chrnsv commented on courseProject/Sources/courseProject/Delete.swift
> +        for (word, translations) in dictionary {
Да, я перепутал, подумал, что это класс поиска, но проблема тут (и в классе поиска) скорее в том, что делаем в классе две функции

1. Что-то ищем/удаляем
2. Решаем как выводить и выводим

Лучше сделать так, чтобы у поиска/удаления был какой-то результат, который бы потом можно было передать в `output` и тот уже по результату определил как его выводить

2020-11-13 16:48 UTC, chrnsv approved these changes

2020-11-13 16:48 UTC, chrnsv commented on courseProject/Sources/courseProject/Output.swift
> +    func outputting(key: String) {
тогда уж `value` или `message`, но, наверное, не `key`

2020-11-13 16:48 UTC, chrnsv commented on courseProject/Sources/courseProject/Output.swift
> +        let alternativeOutput = false
А точно везде `false`?

2020-11-14 06:45 UTC, KabStas commented on courseProject/Sources/courseProject/Output.swift
> +    func outputting(key: String) {
исправил

2020-11-14 06:47 UTC, KabStas commented on courseProject/Sources/courseProject/Output.swift
> +        let alternativeOutput = false
здесь точно везде false

2020-11-14 06:50 UTC, merged