Lesson6
KabStas/CourseProject pull request #4
Opened 2020-11-21 14:09 UTC by KabStas

2020-11-21 16:55 UTC, chrnsv requested changes

2020-11-21 16:55 UTC, chrnsv commented on courseProject/Sources/App/App.swift
> +public class Container {
А зачем `public`?

2020-11-21 16:55 UTC, chrnsv commented on courseProject/Sources/App/App.swift
> +        return 1
Получается, что любой успех – 0, а любая неудача – 1, это возможное поведение, но что если тест, который завершился неудачей, но не потому что ты передал неверные параметры, а потому что он не смог считать словарь

2020-11-21 16:55 UTC, chrnsv commented on courseProject/Sources/App/Arguments.swift
> +    case error(error: Int32)
А этот кейс обрабатывается?

2020-11-21 16:55 UTC, chrnsv commented on courseProject/Sources/App/ArgumentsParser.swift
> +            return .error(error: 1)
А сообщение все равно хочется увидеть, даже если была ошибка

2020-11-21 16:55 UTC, chrnsv commented on courseProject/Sources/App/Result.swift
> +public enum Result {
Обычно, стараемся получить максимум информации о том, какая ошибка произошла, чтобы потом понять что чинить, тут получилось наоборот, куча разных успехов (при том, что мы, обычно, знаем что запустили (search/update/delete...)), но только одна общая ошибка. Забавно, кстати, будет, если search вернет DeletingSuccess:) А Result решил не использовать или не разобрался как?

2020-11-21 16:55 UTC, chrnsv commented on courseProject/Sources/App/Search.swift
> +                output.outputting(value: "Not found")
Но пробел-то лишний)

2020-11-21 16:55 UTC, chrnsv commented on courseProject/Tests/AppTests/ArgumentsParserTests.swift
> +                XCTFail()
Давай в таких фэйлах писать сообщения о том, что пошло не так

2020-11-21 16:55 UTC, chrnsv commented on courseProject/Tests/AppTests/ArgumentsParserTests.swift
> +
Нужны еще тесты, которые должны возвращать ошибку/помощь

2020-11-21 16:55 UTC, chrnsv commented on courseProject/Tests/AppTests/DeleteTests.swift
> +        XCTAssertEqual(results, Result.DeletingSuccess)
Нужны еще проверки работы с зависимостями

2020-11-21 16:55 UTC, chrnsv commented on courseProject/Tests/AppTests/Mock/GetDataMock.swift
> +	var getDataParameters: ()!
форматирование

2020-11-21 16:55 UTC, chrnsv commented on courseProject/Tests/AppTests/Mock/OutputMock.swift
> +    var outputingResult: ()
Если функция ничего оне возвращает, то `result` можно не писать

2020-11-21 16:55 UTC, chrnsv commented on courseProject/Tests/AppTests/Mock/PutDataMock.swift
> +        putDataParameters = ["cat": ["rus": "Кот"]]
это почему?)

2020-11-21 16:55 UTC, chrnsv commented on courseProject/Tests/test.sh
> +test "Один из ключей правильный при обновление словаря" "update kit -k cat -t ukr" 1
Вот тут ок, можно придумать еще несколько неуспешных тестов, но это факультативно

2020-11-22 06:46 UTC, KabStas commented on courseProject/Sources/App/App.swift
> +public class Container {
Ну просто ) Исправил

2020-11-22 07:15 UTC, KabStas commented on courseProject/Tests/AppTests/Mock/OutputMock.swift
> +    var outputingResult: ()
Убрал

2020-11-22 07:15 UTC, KabStas commented on courseProject/Tests/AppTests/Mock/PutDataMock.swift
> +        putDataParameters = ["cat": ["rus": "Кот"]]
putDataParameters = dictionary ) Исправил

2020-11-22 11:40 UTC, KabStas commented on courseProject/Tests/test.sh
> +test "Один из ключей правильный при обновление словаря" "update kit -k cat -t ukr" 1
Придумал еще несколько

2020-11-26 13:36 UTC, chrnsv approved these changes

2020-11-26 13:36 UTC, chrnsv commented on courseProject/Sources/App/ArgumentsParser.swift
> +public class ArgumentsParser: ArgumentsParserProtocol {
Давай все-таки `public` везде уберем, где не нужен

2020-11-26 14:18 UTC, merged